//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexbaze.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flexbaze.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accidents.
        /// </summary>
        public static string AccidentsButton {
            get {
                return ResourceManager.GetString("AccidentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All cells.
        /// </summary>
        public static string AllCells {
            get {
                return ResourceManager.GetString("AllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Assign.
        /// </summary>
        public static string AssignLabel {
            get {
                return ResourceManager.GetString("AssignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best Team Leader.
        /// </summary>
        public static string BestTeamLeaderLabel {
            get {
                return ResourceManager.GetString("BestTeamLeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BREAKDOWN.
        /// </summary>
        public static string BreakDownLabel {
            get {
                return ResourceManager.GetString("BreakDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broken piece.
        /// </summary>
        public static string BrokenPiece {
            get {
                return ResourceManager.GetString("BrokenPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cause.
        /// </summary>
        public static string CauseLabel {
            get {
                return ResourceManager.GetString("CauseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell.
        /// </summary>
        public static string CellLabel {
            get {
                return ResourceManager.GetString("CellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chronology.
        /// </summary>
        public static string Chronology {
            get {
                return ResourceManager.GetString("Chronology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string ClosedLabel {
            get {
                return ResourceManager.GetString("ClosedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detail.
        /// </summary>
        public static string DetailPageTitle {
            get {
                return ResourceManager.GetString("DetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string DetailsLabel {
            get {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOWN.
        /// </summary>
        public static string DownLabel {
            get {
                return ResourceManager.GetString("DownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Element.
        /// </summary>
        public static string ElementLabel {
            get {
                return ResourceManager.GetString("ElementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elements.
        /// </summary>
        public static string ElementsLabel {
            get {
                return ResourceManager.GetString("ElementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failure in mold.
        /// </summary>
        public static string FailureMold {
            get {
                return ResourceManager.GetString("FailureMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5 minutes ago.
        /// </summary>
        public static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14 minutes ago.
        /// </summary>
        public static string FourteenMinutes {
            get {
                return ResourceManager.GetString("FourteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDLE.
        /// </summary>
        public static string IdleLabel {
            get {
                return ResourceManager.GetString("IdleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidents.
        /// </summary>
        public static string IncidentsButton {
            get {
                return ResourceManager.GetString("IncidentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A user with a serious injury has been reported in Cell 4..
        /// </summary>
        public static string InjuredUser {
            get {
                return ResourceManager.GetString("InjuredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in.
        /// </summary>
        public static string InLabel {
            get {
                return ResourceManager.GetString("InLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Process.
        /// </summary>
        public static string InProcessLabel {
            get {
                return ResourceManager.GetString("InProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lack of material.
        /// </summary>
        public static string LackMaterial {
            get {
                return ResourceManager.GetString("LackMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lack of mold.
        /// </summary>
        public static string LackMold {
            get {
                return ResourceManager.GetString("LackMold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leak.
        /// </summary>
        public static string LeakLabel {
            get {
                return ResourceManager.GetString("LeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Machine status.
        /// </summary>
        public static string MachineStatusTitle {
            get {
                return ResourceManager.GetString("MachineStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material was requested with No. 17293 because the machine was stopping the operation..
        /// </summary>
        public static string MainDetail {
            get {
                return ResourceManager.GetString("MainDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string MasterMenuChat {
            get {
                return ResourceManager.GetString("MasterMenuChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        public static string MasterMenuDashboard {
            get {
                return ResourceManager.GetString("MasterMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string MasterMenuEnglish {
            get {
                return ResourceManager.GetString("MasterMenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        public static string MasterMenuEvents {
            get {
                return ResourceManager.GetString("MasterMenuEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string MasterMenuLanguage {
            get {
                return ResourceManager.GetString("MasterMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        public static string MasterMenuNotifications {
            get {
                return ResourceManager.GetString("MasterMenuNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign out.
        /// </summary>
        public static string MasterMenuSignOut {
            get {
                return ResourceManager.GetString("MasterMenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string MasterMenuSpanish {
            get {
                return ResourceManager.GetString("MasterMenuSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        public static string MasterMenuSupport {
            get {
                return ResourceManager.GetString("MasterMenuSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello .
        /// </summary>
        public static string MasterMenuTitle {
            get {
                return ResourceManager.GetString("MasterMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measures not allowed.
        /// </summary>
        public static string MeasuresNotAllowed {
            get {
                return ResourceManager.GetString("MeasuresNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Milky piece.
        /// </summary>
        public static string MilkyPiece {
            get {
                return ResourceManager.GetString("MilkyPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minor incident.
        /// </summary>
        public static string MinorIncident {
            get {
                return ResourceManager.GetString("MinorIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell 2 has slowed down due to lack of material..
        /// </summary>
        public static string MinusSpeed {
            get {
                return ResourceManager.GetString("MinusSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mold routine.
        /// </summary>
        public static string MoldRoutine {
            get {
                return ResourceManager.GetString("MoldRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string MonthButton {
            get {
                return ResourceManager.GetString("MonthButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notifications.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OEE Cells.
        /// </summary>
        public static string OEECellsTitle {
            get {
                return ResourceManager.GetString("OEECellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OEE.
        /// </summary>
        public static string OEELabel {
            get {
                return ResourceManager.GetString("OEELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 hour ago.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string OpenLabel {
            get {
                return ResourceManager.GetString("OpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packed.
        /// </summary>
        public static string PackedLabel {
            get {
                return ResourceManager.GetString("PackedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pigment needed.
        /// </summary>
        public static string PigmentNeeded {
            get {
                return ResourceManager.GetString("PigmentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plant.
        /// </summary>
        public static string PlantLabel {
            get {
                return ResourceManager.GetString("PlantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progress.
        /// </summary>
        public static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quality.
        /// </summary>
        public static string QualityLabel {
            get {
                return ResourceManager.GetString("QualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw material missing.
        /// </summary>
        public static string RawMaterial {
            get {
                return ResourceManager.GetString("RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested by:.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolved by:.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sampling.
        /// </summary>
        public static string SamplingLabel {
            get {
                return ResourceManager.GetString("SamplingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrap causes.
        /// </summary>
        public static string ScrapCausesTitle {
            get {
                return ResourceManager.GetString("ScrapCausesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrap.
        /// </summary>
        public static string ScrapTitle {
            get {
                return ResourceManager.GetString("ScrapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security.
        /// </summary>
        public static string SecurityLabel {
            get {
                return ResourceManager.GetString("SecurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most common stoppages.
        /// </summary>
        public static string StoppagesTitle {
            get {
                return ResourceManager.GetString("StoppagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Production has stopped..
        /// </summary>
        public static string StoppedProduction {
            get {
                return ResourceManager.GetString("StoppedProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support timeline.
        /// </summary>
        public static string SupportTimeline {
            get {
                return ResourceManager.GetString("SupportTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        public static string SupportTitle {
            get {
                return ResourceManager.GetString("SupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has been closed..
        /// </summary>
        public static string TicketClosed {
            get {
                return ResourceManager.GetString("TicketClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticket.
        /// </summary>
        public static string TicketLabel {
            get {
                return ResourceManager.GetString("TicketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Availability.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        public static string TodayButton {
            get {
                return ResourceManager.GetString("TodayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unread.
        /// </summary>
        public static string UnreadLabel {
            get {
                return ResourceManager.GetString("UnreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UP.
        /// </summary>
        public static string UpLabel {
            get {
                return ResourceManager.GetString("UpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string UsernamePlaceHolder {
            get {
                return ResourceManager.GetString("UsernamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week.
        /// </summary>
        public static string WeekButton {
            get {
                return ResourceManager.GetString("WeekButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yesterday.
        /// </summary>
        public static string YesterdayLabel {
            get {
                return ResourceManager.GetString("YesterdayLabel", resourceCulture);
            }
        }
    }
}
